# Generated by Django 3.0.3 on 2020-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaupungin_osa', models.CharField(max_length=30)),
                ('alueen_nimi', models.CharField(max_length=30)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('pinta_ala', models.IntegerField()),
            ],
        ),
    ]
